main:
  - name: 主页
    url: /
    weight: 10
  - name: 新闻
    url: /post
    weight: 11
  - name: 研究小组
    url: /research
    weight: 12
  # - name: 活动
  #   url: /event
  #   weight: 13
  - name: 出版物
    url: publication/
    weight: 20
  # - name: 项目
  #   url: projects/
  #   weight: 30
  # - name: 教学
  #   url: teaching/
  #   weight: 40
